name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
      - name: Set the values
        run: |
          echo "{CLIENT_ID}={process.env.CLIENT_ID}" >> "$GITHUB_ENV"
          echo "{CLIENT_SECRET}={process.env.CLIENT_SECRET}" >> "$GITHUB_ENV"
          echo "{ISSUER}={process.env.ISSUER}" >> "$GITHUB_ENV"
      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          config-file: cypress.config.js
          start: npm run test
          wait-on: 'http://localhost:3000'
          browser: chrome